name: Second Workflow

on:
  issues:
    types: [opened]

jobs:
  issue_job: 
    runs-on: ubuntu-latest
    steps:
      - name: Check issue metadata
        run: echo "${{ github.event.issue.title }}"
